# Generated by Django 4.2.3 on 2023-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_associationsociete_societe1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('correspondance', models.CharField(max_length=250)),
            ],
        ),
    ]
