# Generated by Django 4.2.3 on 2023-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_indentite'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='password',
            field=models.CharField(default='m1234', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='server',
            field=models.CharField(default='192.168.1.161', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='user',
            field=models.CharField(default='reader', max_length=150, null=True),
        ),
    ]
