# Generated by Django 4.2.3 on 2023-08-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_societe_password_societe_server_societe_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=50, unique=True)),
                ('ecPiece', models.IntegerField()),
                ('ecRefPiece', models.CharField(max_length=50)),
                ('ecNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IntercoHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interco', models.CharField(max_length=10, null=True, unique=True)),
                ('tableau1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_tableau1', to='home.tableau')),
                ('tableau2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_tableau2', to='home.tableau')),
            ],
        ),
    ]
