# Generated by Django 4.2.3 on 2023-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_intercohistorique_tableau1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='base',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
