# Generated by Django 4.2.3 on 2023-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_intercohistorique_tableau1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercohistorique',
            name='interco',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
